# What is the tensor?

When you do programming of tensorflow, _Tensor is everything_. I mean the programming of Tensorflow is building a graph that freely transport tensors. Tensor in Tensorflow is a **generalization of vectos and matrices**. it potentially contains higher dimensions. Internally, Tensorflow representas tensors as n-dimension arrays of base datatype(**string, int32, float32 and so on**). 

A **tf.Tensor** has two properties : 

   - a data type(float32, int32 or string and so on): each element in the Tensor has the same datatype. 
   
   - a shape: The number of dimension tensor has and the size of each dimension
       - shape can be partially or fully known.
       
There are some types of tensor :

   - tf.Variable,  tf.Constant, tf.Placeholder, tf.SparseTensor.
    
In the **key point**, with exceptoin of **tf.Variable**, **The value of a tensor is immutable**, which means that in the context of a single execution tensors only have a single value.


## Rank vs Shape 

   - rank: tensor object's number of dimensions.
   
```python
# Rank 0 (scalar)
animal = tf.Variable("Elephant", tf.string)
integer = tf.Variable(451, tf.int32)
# Rank 1 (1-dimension, vector)
floating_array  = tf.Variable([3.14159, 2.71828], tf.float32)
# Rank 2 (2-dimension, matrix)
# Normally, A rank 2 tensor object consists of as least one row and at least one column.
matrix = tf.Variable([[7],[11]], tf.int32)
# To check what version of rank each variables is?
rank0 = tf.rank(animal)
rank1 = tf.rank(floating_array)
rank2 = tf.rank(matrix)
```


   - shape: tensor object's the number of elements in each dimension. 

```python
# Every element in a tensor is one 
rank_three_tensor = tf.ones([3, 4, 5])
# To check the shape of a tensor
tf.shape(rank_three_tensor)
# To reshape of a tensor(rank 2)
matrix = tf.reshape(rank_three_tensor, [6, 10])
# To Check what kind of shape matrix has
tf.shape(matrix)
tf.shape(matrix)[0]
tf.shape(matrix)[1]
```

There are three notation used in Tensorflow:

   - rank, shape, dimencsion number

|  Rank  |      Shape      | dimension number |    Example    |
| :----: | :------------- | ---------------- | :------------- |
| 0 | [] | 0-D | A 0-D tensor, A scalar. |
| 1 | [D0] | 1-D | A 1-D tensor with shape[3]. |
| 2 | [D0, D1] | 2-D | A 2-D tensor with shape[3,2]|
| n | [D0, D0, ... , Dn-1] | n-D | A n-D tensor with shape[D0, D1,..., Dn-1] |

If you don't specify datatye of python object, when you create a **tf.tensor**, Tensorflow automatically choose datatype that can represent your data. 

   - Python's Integers --> tf.int32
   
   
   - Python's Floating point numbers ---> tf.float32

# Reference

   - [Guides r0.12](https://www.tensorflow.org/versions/r0.12/how_tos/variables/)
   
   - [Intialization function of tensorflow r0.12](https://www.tensorflow.org/versions/r0.12/api_docs/python/constant_op/)
      
   - [Tensors section of Programmer's guide of Tensorflow](https://www.tensorflow.org/programmers_guide/tensors)
   
   - [Variables section of Programmer's guide of Tensorflow](https://www.tensorflow.org/programmers_guide/variables)

In [1]:
import sys
import tensorflow as tf

print("=== System version ===")
print(sys.version, "\n")

print("=== Tensorflow version ===")
print(tf.__version__, "\n")

=== System version ===
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] 

=== Tensorflow version ===
1.4.0 



In [2]:
# === What is the rank of tensor? ===
# Rank 0 (scalar)
animal = tf.Variable("Elephant", tf.string)
integer = tf.Variable(451, tf.int32)
# Rank 1 (1-dimension, vector)
floating_array  = tf.Variable([3.14159, 2.71828], tf.float32)
# Rank 2 (2-dimension, matrix)
# Normally, A rank 2 tensor object consists of as least one row and at least one column.
matrix = tf.Variable([[7],[11]], tf.int32)
# To check what version of rank each variables is?
rank0 = tf.rank(animal)
rank1 = tf.rank(floating_array)
rank2 = tf.rank(matrix)

global_init_op = tf.global_variables_initializer() 

with tf.Session() as sess:
    sess.run(global_init_op)
    #print(sess.run([animal, integer, floating_array, matrix, rank0, rank1, rank2]))
    animal_, integer_, floating_array_, matrix_, rank0_, rank1_, rank2_ = sess.run([animal, integer, floating_array, matrix, rank0, rank1, rank2])
    print("=== check each variables ===")
    print("animal:", animal_, "|", "integer:", integer_)
    print("floating array:", floating_array_, "|", "matrix:", matrix_)
    print("rank0:", rank0_, "|", "rank1:", rank1_, "|", "rank2", rank2_)

=== check each variables ===
animal: b'Elephant' | integer: 451
floating array: [ 3.14159012  2.71828008] | matrix: [[ 7]
 [11]]
rank0: 0 | rank1: 1 | rank2 2


In [3]:
# === What is the rank of shape? ===
# Every element in a tensor is one 
rank_three_tensor = tf.ones([3, 2, 1])
# To check the shape of a tensor
shape_rank_three_tensor = tf.shape(rank_three_tensor)
# To reshape of a tensor(rank 2)
matrix = tf.reshape(rank_three_tensor, [1, 6])
# To check evaluating with some number after reshaping 
m = matrix + 2
# To Check what kind of shape matrix has
shape = tf.shape(matrix)
shape0 = tf.shape(matrix)[0]
shape1 = tf.shape(matrix)[1]

global_init_op = tf.global_variables_initializer() 

In [4]:
with tf.Session() as sess:
    sess.run(global_init_op)
    #print(sess.run([rank_three_tensor, shape_rank_three_tensor, matrix, shape, shape0, shape1]))
    rank_three_tensor_, shape_rank_three_tensor_, matrix_, shape_, shape0_, shape1_, m_ = sess.run([rank_three_tensor, shape_rank_three_tensor, matrix, shape, shape0, shape1, m])
    print("=== check each variables ===")
    print("rank three tensor\n:", rank_three_tensor_)
    print("matrix of rank three tensor reshaped:", matrix)
    print("shape of matrix:", shape_, "|", "shape[0] of matrix:", shape0_, "|", "shape[1] of matrix:", shape1_)
    print("matrix + 2 after reshaping:", m_)
    print("\n=== Directly check matrix of rank three tensor reshaped ===")
    print(sess.run(matrix))

=== check each variables ===
rank three tensor
: [[[ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]]]
matrix of rank three tensor reshaped: Tensor("Reshape:0", shape=(1, 6), dtype=float32)
shape of matrix: [1 6] | shape[0] of matrix: 1 | shape[1] of matrix: 6
matrix + 2 after reshaping: [[ 3.  3.  3.  3.  3.  3.]]

=== Directly check matrix of rank three tensor reshaped ===
[[ 1.  1.  1.  1.  1.  1.]]
